server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://valhalla:8002/;
        proxy_set_header Host $host;
    }

    location /photon/ {
        proxy_pass http://photon:2322/;
        proxy_set_header Host $host;
    }
}
